import Head from 'next/head'
import Hero from '../components/Hero'
import Features from '../components/Features'
import Message from '../components/Message'
import Comingup from '../components/ComingUp'
import TargetUsers from '../components/TargetUsers'
import FrequentlyQues from '../components/FrequentlyQues'
import SearchBox from '../components/SearchBox'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>HUST GAMIFICATION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Features />
        <SearchBox />
        <TargetUsers />
        <Message />
        <Comingup />
        <FrequentlyQues />
      </main>
    </>
  )
}